drop table if exists t_available_space;
drop table if exists t_block;
drop table if exists t_student;
drop table if exists t_year;
create table t_available_space (id  integer, day varchar(255) not null, finalHour varchar(255) not null, initialHour varchar(255) not null, block_id bigint not null, student_id bigint not null, primary key (id));
create table t_block (id  integer, name varchar(255) not null, year_id bigint not null, primary key (id));
create table t_student (id  integer, email varchar(255) not null, firstName varchar(255) not null, phoneNumber varchar(255) not null, surname varchar(255) not null, universityId varchar(255) not null, primary key (id));
create table t_year (id  integer, year integer not null, primary key (id));
drop table if exists t_available_space;
drop table if exists t_block;
drop table if exists t_student;
drop table if exists t_year;
create table t_available_space (id  integer, day varchar(255) not null, finalHour varchar(255) not null, initialHour varchar(255) not null, block_id bigint not null, student_id bigint not null, primary key (id));
create table t_block (id  integer, name varchar(255) not null, year_id bigint not null, primary key (id));
create table t_student (id  integer, email varchar(255) not null, firstName varchar(255) not null, phoneNumber varchar(255) not null, surname varchar(255) not null, universityId varchar(255) not null, primary key (id));
create table t_year (id  integer, year integer not null, primary key (id));
